# Generated by Django 3.1.1 on 2020-10-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_song_is_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
